spring:
  profiles: production-psql
  datasource:
    url: jdbc:postgresql://10.0.3.18:5432/usermgtdb?currentSchema=arcgen
    username: postgres
#    password: joy1234
    password: ENC(rYzcd8JP3REMm0kJkMgFPXHYNwj04B3Rk6WZ6gco7QFrNQUSq6y41zN6ab2cDyY6)
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
#    show-sql: true
    properties:
      hibernate:
        ddl-auto: update
#        generate_statistics: true
        format_sql: true
        jdbc: 
          lob:
            non_contextual_creation: true
  logging:
    level:
    org:
      hibernate:
        type: trace
        stat: debug
    file:
        path: .

server:
  address: 172.31.95.49
  port: 443
  http.port: 80
  ssl:
    key-store: ../sslkeys/29-01-2022/springboot_letsencrypt.p12 
    key-store-password: dxr
    keyStoreType: PKCS12
    keyAlias: bootalias
---

spring:
  profiles: develop-psql
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/usermgtdb?currentSchema=arcgen
    username: postgres
    password: dxr1234
#    password: ENC(rYzcd8JP3REMm0kJkMgFPXHYNwj04B3Rk6WZ6gco7QFrNQUSq6y41zN6ab2cDyY6)
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
#    show-sql: true
    properties:
      hibernate:
        ddl-auto: update
#        generate_statistics: true
        format_sql: true
        jdbc: 
          lob:
            non_contextual_creation: true
  logging:
    level:
    org:
      hibernate:
        type: trace
        stat: debug
    root: INFO
    file:
        path: .

server:
#  address: 192.168.68.109
  address: 127.0.0.1
  port: 9000
---

spring:
  profiles:
    active: develop-psql
        

#production-psql
#develop-psql