connect 'jdbc:derby:database/dxrdb;create=true';

CREATE TABLE DXRADMIN.ACCESS_DEF (
	ACCESS_DEF_ID VARCHAR(255) NOT NULL,
	ACCESS_TITLE VARCHAR(255),
	ACCESS_CODE VARCHAR(255),
	ACCESS_DESCRIPTION VARCHAR(255),
	PRIMARY KEY (ACCESS_DEF_ID)
);

CREATE TABLE DXRADMIN.ACCOUNTANT_INFO (
	ACCOUNTANT_INFO_ID VARCHAR(255) NOT NULL,
	ACCOUNTANT_NAME VARCHAR(255),
	ACCOUNTANT_EMAIL VARCHAR(255),
	INVOICE_CLOSING_DATE VARCHAR(255),
	INVOICE_PAYMENT_DATE VARCHAR(255),
	PAYMENT_MODE VARCHAR(255),
	COMPANY_ID VARCHAR(255),
	CONTACT_NO VARCHAR(255),
	PRIMARY KEY (ACCOUNTANT_INFO_ID)
);

CREATE TABLE DXRADMIN.AGREEMENT_COMPANY_INFO (
	AGREEMENT_COMPANY_INFO_ID VARCHAR(255) NOT NULL,
	PERSON_IN_CHARGE_ID VARCHAR(255),
	PAYMENT_METHOD_ID VARCHAR(255),
	ASSIGNED_ROLES VARCHAR(10000),
	AGREEMENT_INFO_ID VARCHAR(255),
	COMPANY_ID VARCHAR(255),
	PRIMARY KEY (AGREEMENT_COMPANY_INFO_ID)
);

CREATE TABLE DXRADMIN.AGREEMENT_INFO (
	AGREEMENT_INFO_ID VARCHAR(255) NOT NULL,
	TITLE VARCHAR(255),
	CREATE_DATE VARCHAR(255),
	VALID_DATE VARCHAR(255),
	AGREEMENT_TYPE VARCHAR(255),
	AGREEMENT_STATUS_ID VARCHAR(255),
	AGREEMENT_REMARK VARCHAR(255),
	DUMPER_COMPANY_ID VARCHAR(255),
	TRANSPORTER_COMPANY_ID VARCHAR(255),
	PROCESSOR_COMPANY_ID VARCHAR(255),
	CREATOR_ROLE VARCHAR(255),
	FIRST_PARTY_ROLE VARCHAR(255),
	SECOND_PARTY_ROLE VARCHAR(255),
	PRIMARY KEY (AGREEMENT_INFO_ID)
);

CREATE TABLE DXRADMIN.AGREEMENT_PROCESS_DEF (
	AGREEMENT_PROCESS_DEF_ID VARCHAR(255) NOT NULL,
	AGREEMENT_PROCESS_DEF VARCHAR(32000),
	PRIMARY KEY (AGREEMENT_PROCESS_DEF_ID)
);

CREATE TABLE DXRADMIN.AGREEMENT_STATUS (
	AGREEMENT_STATUS_ID VARCHAR(255) NOT NULL,
	PROCESS_DEF_ID VARCHAR(255),
	ACTION_ID VARCHAR(255),
	AGREEMENT_ID VARCHAR(255),
	STATUS_DEF_ID VARCHAR(255),
	PRIMARY KEY (AGREEMENT_STATUS_ID)
);

CREATE TABLE DXRADMIN.AGREEMENT_WASTE_PROCESS_INFO (
	AGREEMENT_WASTE_PROCESS_INFO_ID VARCHAR(255) NOT NULL,
	WASTE_DEF_ID VARCHAR(255),
	WASTE_CATEGORY_ID VARCHAR(255),
	PRICE INTEGER,
	AGREEMENT_INFO_ID VARCHAR(255),
	PRIMARY KEY (AGREEMENT_WASTE_PROCESS_INFO_ID)
);

CREATE TABLE DXRADMIN.AGREEMENT_WASTE_TRANSPORT_INFO (
	AGREEMENT_WASTE_TRANSPORT_INFO_ID VARCHAR(255) NOT NULL,
	WASTE_DEF_ID VARCHAR(255),
	WASTE_CATEGORY_ID VARCHAR(255),
	PICK_ZIP_CODE VARCHAR(255),
	PICK_ADDRESS VARCHAR(1000),
	DROP_ZIP_CODE VARCHAR(255),
	DROP_ADDRESS VARCHAR(1000),
	PRICE INTEGER,
	AGREEMENT_INFO_ID VARCHAR(255),
	PRIMARY KEY (AGREEMENT_WASTE_TRANSPORT_INFO_ID)
);

CREATE TABLE DXRADMIN.BANK_ACCOUNT_INFO (
	BANK_ACCOUNT_ID VARCHAR(255) NOT NULL,
	BANK_NAME VARCHAR(255),
	BRANCH_NAME VARCHAR(255),
	ACCOUNT_NUMBER VARCHAR(255),
	ACCOUNT_NAME VARCHAR(255),
	COMPANY_ID VARCHAR(255),
	PRIMARY KEY (BANK_ACCOUNT_ID)
);

CREATE TABLE DXRADMIN.BASE_PRICE (
	BASE_PRICE_ID VARCHAR(255) NOT NULL,
	TRANSPORT_PRICE DOUBLE,
	PROCESSING_PRICE DOUBLE,
	REMARKS VARCHAR(32000),
	FRONTEND_DATE VARCHAR(255),
	BACKEND_DATE VARCHAR(255),
	COMPANY_WASTE_ID VARCHAR(255),
	PRIMARY KEY (BASE_PRICE_ID)
);

CREATE TABLE DXRADMIN.BRANCH_BUSINESS_TYPE (
	BRANCH_BUSINESS_TYPE_ID VARCHAR(255) NOT NULL,
	BRANCH_INFO_ID VARCHAR(255),
	BRANCH_BUSINESS_CATEGORY_ID_LIST VARCHAR(255),
	PRIMARY KEY (BRANCH_BUSINESS_TYPE_ID)
);

CREATE TABLE DXRADMIN.BRANCH_INFO (
	BRANCH_INFO_ID VARCHAR(255) NOT NULL,
	BRANCH_NAME VARCHAR(255),
	BRANCH_ADDRESS VARCHAR(255),
	BRANCH_CONTACT_NO VARCHAR(255),
	BRANCH_FAX_NUMBER VARCHAR(255),
	BRANCH_MANAGER_NAME VARCHAR(255),
	FRONTEND_DATE VARCHAR(255),
	BACKEND_DATE VARCHAR(255),
	COMPANY_INFO_ID VARCHAR(255),
	REMARKS VARCHAR(32000),
	ZIPCODE VARCHAR(255),
	PRIMARY KEY (BRANCH_INFO_ID)
);

CREATE TABLE DXRADMIN.CARBON_EMISSION_METHOD_INFO (
	EMISSION_METHOD_ID VARCHAR(255) NOT NULL,
	METHOD_TITLE VARCHAR(255),
	CODE VARCHAR(255),
	DESCRIPTIONS VARCHAR(555),
	EMISSION_QUNTITY DOUBLE,
	OPERATION_TYPE_ID VARCHAR(255),
	PRIMARY KEY (EMISSION_METHOD_ID)
);

CREATE TABLE DXRADMIN.COMPANY_ADMIN_ACCESS (
	COMPANY_ADMIN_ACCESS_ID VARCHAR(255) NOT NULL,
	COMPANY_ADMIN_ACCESS VARCHAR(32000),
	UPDATE_DATE VARCHAR(255),
	PRIMARY KEY (COMPANY_ADMIN_ACCESS_ID)
);

CREATE TABLE DXRADMIN.COMPANY_CATEGORY (
	COMPANY_CATEGORY_ID VARCHAR(255) NOT NULL,
	CATEGORY_NAME VARCHAR(255),
	CATEGORY_CODE VARCHAR(255),
	CATEGORY_DESCRIPTION VARCHAR(1024),
	PRIMARY KEY (COMPANY_CATEGORY_ID)
);

CREATE TABLE DXRADMIN.COMPANY_INFO (
	COMPANY_INFO_ID VARCHAR(255) NOT NULL,
	COMPANY_NAME VARCHAR(255),
	COMPANY_ADDRESS VARCHAR(255),
	COMPANY_EMAIL VARCHAR(255),
	COMPANY_CONTACT VARCHAR(255),
	REPRESENTATIVE_NAME VARCHAR(255),
	REPRESENTATIVE_MAIL VARCHAR(255),
	COMPANY_FAX_NUMBER VARCHAR(255),
	CORPORATE_REG_NO VARCHAR(255),
	WASTE_PROCESSING_LICENCE_NO VARCHAR(255),
	WASTE_PROCESSING_LICENCE_BYTES BLOB(2147483647),
	ACCOUNTANT_NAME VARCHAR(255),
	ACCOUNTANT_EMAIL VARCHAR(255),
	NOTIFICATION_ID VARCHAR(255),
	SUBSCRIPTION_ID VARCHAR(255),
	FRONTEND_DATE VARCHAR(255),
	BACKEND_DATE VARCHAR(255),
	ZIPCODE VARCHAR(255),
	REMARKS VARCHAR(255),
	COMPANY_SEAL BLOB(2147483647),
	PRIMARY KEY (COMPANY_INFO_ID)
);

CREATE TABLE DXRADMIN.COMPANY_TYPE_INFO (
	COMPANY_TYPE_INFO_ID VARCHAR(255) NOT NULL,
	COMPANY_ID VARCHAR(255),
	COMPANY_CATEGORY_ID_LIST VARCHAR(255),
	PRIMARY KEY (COMPANY_TYPE_INFO_ID)
);

CREATE TABLE DXRADMIN.COMPANY_WASTE_DEF (
	COMPANY_WASTE_DEF_ID VARCHAR(255) NOT NULL,
	COMPANY_ID VARCHAR(255),
	WASTE_DEF_ID VARCHAR(255),
	PRIMARY KEY (COMPANY_WASTE_DEF_ID)
);

CREATE TABLE DXRADMIN.COMPANY_WASTE_OPERATION_METHOD_INFO (
	COMPANY_WASTE_OPERATION_METHOD_ID VARCHAR(255) NOT NULL,
	METHOD_ID VARCHAR(255),
	WASTE_ID VARCHAR(255),
	COMPANY_ID VARCHAR(255),
	METHOD_TYPE_ID VARCHAR(255),
	PRIMARY KEY (COMPANY_WASTE_OPERATION_METHOD_ID)
);

CREATE TABLE DXRADMIN.DISPOSAL_INFO (
	DISPOSAL_INFO_ID VARCHAR(255) NOT NULL,
	PICK_START_DATE VARCHAR(255),
	PICK_END_DATE VARCHAR(255),
	QUANTITY DOUBLE,
	PROJECT_INFO_ID VARCHAR(255),
	COLLECTION_ID VARCHAR(255),
	IS_PARENT VARCHAR(255),
	PRIMARY KEY (DISPOSAL_INFO_ID)
);

CREATE TABLE DXRADMIN.DUMPING_EMISSION_INFO (
	DUMPING_EMISSION_ID VARCHAR(255) NOT NULL,
	COMPANY_ID VARCHAR(255),
	QUANTITY DOUBLE,
	DATE_TIME VARCHAR(255),
	WASTE_ITEM_ID VARCHAR(255),
	WASTE_TITLE VARCHAR(255),
	UNIT VARCHAR(255),
	PICK_ID VARCHAR(10000),
	PRIMARY KEY (DUMPING_EMISSION_ID)
);

CREATE TABLE DXRADMIN.DXR_ADMIN_ACCESS (
	DXR_ADMIN_ACCESS_ID VARCHAR(255) NOT NULL,
	DXR_ADMIN_ACCESS VARCHAR(32000),
	UPDATE_DATE VARCHAR(255),
	PRIMARY KEY (DXR_ADMIN_ACCESS_ID)
);

CREATE TABLE DXRADMIN.FAQ_INFO (
	FAQ_INFO_ID VARCHAR(255) NOT NULL,
	FAQ_INFO_QUESTION VARCHAR(255),
	FAQ_INFO_ANSWER VARCHAR(10000),
	FAQ_TYPE_ID VARCHAR(255),
	FRONTEND_DATE VARCHAR(255),
	BACKEND_DATE VARCHAR(255),
	PRIMARY KEY (FAQ_INFO_ID)
);

CREATE TABLE DXRADMIN.FAQ_TYPE (
	FAQ_TYPE_ID VARCHAR(255) NOT NULL,
	FAQ_TYPE VARCHAR(255),
	FAQ_TYPE_DESCRIPTION VARCHAR(512),
	FRONTEND_DATE VARCHAR(255),
	BACKEND_DATE VARCHAR(255),
	PRIMARY KEY (FAQ_TYPE_ID)
);

CREATE TABLE DXRADMIN.GASOLINE_TYPE (
	GASOLINE_TYPE_ID VARCHAR(255) NOT NULL,
	TITLE VARCHAR(512),
	MEASUREMENT_UNIT VARCHAR(255),
	CARBON_EMISSION_QUANTITY DOUBLE,
	FUEL_QUANTITY DOUBLE,
	PRIMARY KEY (GASOLINE_TYPE_ID)
);

CREATE TABLE DXRADMIN.INQUIRY_INFO (
	INQUIRY_INFO_ID VARCHAR(255) NOT NULL,
	COMPANY_NAME VARCHAR(255),
	PERSON_NAME VARCHAR(255),
	CONTACT_NO VARCHAR(255),
	EMAIL VARCHAR(255),
	INQUIRY_TITLE VARCHAR(255),
	INQUIRY_DETAIL VARCHAR(255),
	AGREED_TERMS VARCHAR(255),
	DATE_TIME VARCHAR(255),
	IS_HUMAN VARCHAR(255),
	IS_AGREE VARCHAR(255),
	PRIMARY KEY (INQUIRY_INFO_ID)
);

CREATE TABLE DXRADMIN.INQUIRY_REPLY (
	INQUIRY_REPLY_ID VARCHAR(255) NOT NULL,
	REPLY_DATE VARCHAR(255),
	REPLY VARCHAR(255),
	INQUIRY_ID VARCHAR(255),
	IS_ADMIN VARCHAR(255),
	PRIMARY KEY (INQUIRY_REPLY_ID)
);

CREATE TABLE DXRADMIN.INQUIRY_RESPONSE (
	INQUIRY_RESPONSE_ID VARCHAR(255) NOT NULL,
	RESPONSE VARCHAR(10000),
	DATE_TIME VARCHAR(255),
	INQUIRY_INFO_ID VARCHAR(255),
	PRIMARY KEY (INQUIRY_RESPONSE_ID)
);

CREATE TABLE DXRADMIN.INQUIRY_USER_LOGIN_INFO (
	INQUIRY_USER_LOGIN_INFO_ID VARCHAR(255) NOT NULL,
	CODE VARCHAR(255),
	EMAIL VARCHAR(255),
	PRIMARY KEY (INQUIRY_USER_LOGIN_INFO_ID)
);

CREATE TABLE DXRADMIN.INVOICE_GEN_DATE (
	INVOICE_GEN_DATE_ID VARCHAR(255) NOT NULL,
	COMPANY_ID VARCHAR(255),
	INVOICE_GEN_DATE VARCHAR(255),
	PRIMARY KEY (INVOICE_GEN_DATE_ID)
);

CREATE TABLE DXRADMIN.INVOICE_INFO (
	INVOICE_ID VARCHAR(255) NOT NULL,
	INVOICE_NO VARCHAR(255),
	INVOICE_SUBJECT VARCHAR(255),
	BILL_AMOUNT VARCHAR(255),
	REMARK VARCHAR(255),
	INVOICE_DATE VARCHAR(255),
	INVOICE_STATUS VARCHAR(100),
	GENERATOR_COMP_INFO VARCHAR(32500),
	RECEIVE_COMP_INFO VARCHAR(32500),
	MANIFESTO_LIST_BYTES BLOB(2147483647),
	PRIMARY KEY (INVOICE_ID)
);

CREATE TABLE DXRADMIN.INVOICE_PROCESS_DEF (
	INVOICE_PROCESS_DEF_ID VARCHAR(255) NOT NULL,
	INVOICE_PROCESS_DEF VARCHAR(32500),
	PRIMARY KEY (INVOICE_PROCESS_DEF_ID)
);

CREATE TABLE DXRADMIN.INVOICE_REPORT_DATA (
	INVOICE_REPORT_ID VARCHAR(255) NOT NULL,
	INVOICE_INFO_ID VARCHAR(255),
	INVOICE_REPORT_DATA VARCHAR(32500),
	PRIMARY KEY (INVOICE_REPORT_ID)
);

CREATE TABLE DXRADMIN.LANGUAGE_COMPETENCY (
	LANGUAGE_COMPETENCY_ID VARCHAR(255) NOT NULL,
	BACKEND_DATE VARCHAR(255),
	FRONTEND_DATE VARCHAR(255),
	LANGUAGE_JSON_BYTES BLOB(2147483647),
	PRIMARY KEY (LANGUAGE_COMPETENCY_ID)
);

CREATE TABLE DXRADMIN.MENIFESTO_INFO (
	MENIFESTO_INFO_ID VARCHAR(255) NOT NULL,
	MENIFESTO_UNIQUE_ID VARCHAR(255),
	MENIFESTO_CREATE_DATE VARCHAR(255),
	TRIP_ID_LIST VARCHAR(10000),
	PROJECT_ID VARCHAR(255),
	WASTE_ID VARCHAR(255),
	TRIP_ID_DEF VARCHAR(32000),
	PICK_ID_DEF VARCHAR(32000),
	PROJECT_NAME VARCHAR(255),
	CREATOR VARCHAR(255),
	FIRST_PARTY VARCHAR(255),
	SECOND_PARTY VARCHAR(255),
	AGGREMENT_INFO VARCHAR(32000),
	MENIFESTO_STATUS VARCHAR(50),
	PRIMARY KEY (MENIFESTO_INFO_ID)
);

CREATE TABLE DXRADMIN.MENU_CATEGORY (
	MENU_CATEGORY_ID VARCHAR(255) NOT NULL,
	CODE VARCHAR(255),
	DESCRIPTION VARCHAR(255),
	PRIMARY KEY (MENU_CATEGORY_ID)
);

CREATE TABLE DXRADMIN.MENU_DEF (
	MENU_ID VARCHAR(255) NOT NULL,
	MENU_TITLE_ENG VARCHAR(255),
	MENU_TITLE_JPN VARCHAR(255),
	MENU_URL VARCHAR(255),
	PARENT_SEGMENT VARCHAR(255),
	PARENT_DEF VARCHAR(255),
	MENU_TYPE_ID VARCHAR(255),
	MENU_CATEGORY_ID VARCHAR(255),
	PRIMARY KEY (MENU_ID)
);

CREATE TABLE DXRADMIN.MENU_ROLE_ACCESS (
	MENU_ROLE_ACCESS_ID VARCHAR(255) NOT NULL,
	MENU_DEF_ID VARCHAR(255),
	ROLE_ACCESS_LIST VARCHAR(32000),
	PRIMARY KEY (MENU_ROLE_ACCESS_ID)
);

CREATE TABLE DXRADMIN.MENU_ROLE_DEF (
	MENU_ROLE_DEF_ID VARCHAR(255) NOT NULL,
	MENU_ID VARCHAR(255),
	ROLE_DEF_LIST VARCHAR(255),
	PRIMARY KEY (MENU_ROLE_DEF_ID)
);

CREATE TABLE DXRADMIN.MENU_TYPE (
	MENU_TYPE_ID VARCHAR(255) NOT NULL,
	MENU_TYPE_TITLE VARCHAR(255),
	MENU_TYPE_CODE VARCHAR(255),
	MENU_TYPE_DESCRIPTION VARCHAR(255),
	PRIMARY KEY (MENU_TYPE_ID)
);

CREATE TABLE DXRADMIN.NOTIFICATION (
	NOTIFICATION_ID VARCHAR(255) NOT NULL,
	NOTIFICATION_STATE VARCHAR(255),
	NOTIFICATION_CODE VARCHAR(255),
	PRIMARY KEY (NOTIFICATION_ID)
);

CREATE TABLE DXRADMIN.OPERATION_TYPE (
	OPERATION_TYPE_ID VARCHAR(255) NOT NULL,
	CODE VARCHAR(512),
	OPERATION_TITLE VARCHAR(255),
	PRIMARY KEY (OPERATION_TYPE_ID)
);

CREATE TABLE DXRADMIN.PACKAGE_INFO (
	PACKAGE_INFO_ID VARCHAR(255) NOT NULL,
	SIZE DOUBLE,
	NUMBER_OF_PACKAGE INTEGER,
	QUANTITY DOUBLE,
	PICK_ID VARCHAR(255),
	DISPOSE_ID VARCHAR(255),
	TRIP_ID VARCHAR(255),
	IS_LUMPSUM VARCHAR(255),
	PRIMARY KEY (PACKAGE_INFO_ID)
);

CREATE TABLE DXRADMIN.PARTNER_APROVAL_STATUS (
	PARTNER_APROVAL_STATUS_ID VARCHAR(255) NOT NULL,
	AGREEMENT_ID VARCHAR(255),
	PARTNER_COMPANY_ID VARCHAR(255),
	PARTNER_COMPANY_ROLE VARCHAR(255),
	PRIMARY KEY (PARTNER_APROVAL_STATUS_ID)
);

CREATE TABLE DXRADMIN.PARTNER_COMPANY_INFO (
	PARTNER_COMPANY_INFO_ID VARCHAR(255) NOT NULL,
	COMPANY_ID VARCHAR(255),
	PARTNER_ID VARCHAR(255),
	PRIMARY KEY (PARTNER_COMPANY_INFO_ID)
);

CREATE TABLE DXRADMIN.PAYMENT_METHOD_INFO (
	PAYMENT_METHOD_INFO_ID VARCHAR(255) NOT NULL,
	BANK_ACCOUNT_ID VARCHAR(255),
	BANK_NAME VARCHAR(255),
	BRANCH_NAME VARCHAR(255),
	ACCOUNT_NUMBER VARCHAR(255),
	ACCOUNT_NAME VARCHAR(255),
	ACCOUNT_TYPE VARCHAR(255),
	AGREEMENT_INFO_ID VARCHAR(255),
	COMPANY_ID VARCHAR(255),
	PRIMARY KEY (PAYMENT_METHOD_INFO_ID)
);

CREATE TABLE DXRADMIN.PICK_INFO (
	PICK_INFO_ID VARCHAR(255) NOT NULL,
	QUANTITY DOUBLE,
	DISPOSAL_ID VARCHAR(255),
	TRIP_ID VARCHAR(255),
	LOAD_STATUS VARCHAR(255),
	PRIMARY KEY (PICK_INFO_ID)
);

CREATE TABLE DXRADMIN.PREVILAGED_USER (
	PREVILAGED_USER_ID VARCHAR(255) NOT NULL,
	COMPANY_ID VARCHAR(255),
	USER_ID VARCHAR(255),
	ADMIN_TYPE VARCHAR(255),
	PRIMARY KEY (PREVILAGED_USER_ID)
);

CREATE TABLE DXRADMIN.PROCESSING_EMISSION_INFO (
	PROCESSING_EMISSION_ID VARCHAR(255) NOT NULL,
	COMPANY_ID VARCHAR(255),
	QUANTITY DOUBLE,
	DATE_TIME VARCHAR(255),
	WASTE_ITEM_ID VARCHAR(255),
	WASTE_TITLE VARCHAR(255),
	UNIT VARCHAR(255),
	PICK_ID VARCHAR(10000),
	PRIMARY KEY (PROCESSING_EMISSION_ID)
);

CREATE TABLE DXRADMIN.PROJECT_INFO (
	PROJECT_INFO_ID VARCHAR(255) NOT NULL,
	PROJECT_TITLE VARCHAR(255),
	PROJECT_CREATION_DATE VARCHAR(255),
	START_DATE VARCHAR(255),
	END_DATE VARCHAR(255),
	PROJECT_STATUS_INFO_ID VARCHAR(255),
	AGREEMENT_INFO_ID VARCHAR(255),
	COMPANY_ID VARCHAR(255),
	BRANCH_ID VARCHAR(255),
	OPERATING_ADDRESS VARCHAR(255),
	OPERATING_ZIP_CODE VARCHAR(255),
	OPERATING_OFFICE_NAME VARCHAR(255),
	OPERATING_OFFICE_ID VARCHAR(255),
	DUMPER_COMPANY_ID VARCHAR(255),
	TRANSPORTER_COMPANY_ID VARCHAR(255),
	PROCESSOR_COMPANY_ID VARCHAR(255),
	PROJECT_SCHEDULE_STATUS VARCHAR(255),
	PRIMARY KEY (PROJECT_INFO_ID)
);

CREATE TABLE DXRADMIN.PROJECT_PARTNER_APROVAL_STATUS (
	PARTNER_APROVAL_STATUS_ID VARCHAR(255) NOT NULL,
	PROJECT_ID VARCHAR(255),
	PARTNER_ID VARCHAR(255),
	PARTNER_COMPANY_ROLE VARCHAR(255),
	PRIMARY KEY (PARTNER_APROVAL_STATUS_ID)
);

CREATE TABLE DXRADMIN.PROJECT_PROCESS_DEF (
	PROJECT_PROCESS_DEF_ID VARCHAR(255) NOT NULL,
	PROJECT_PROCESS_DEF VARCHAR(32000),
	PRIMARY KEY (PROJECT_PROCESS_DEF_ID)
);

CREATE TABLE DXRADMIN.RECEIVED_PICK (
	RECEIVED_PICK_ID VARCHAR(255) NOT NULL,
	PICK_ID VARCHAR(255),
	QUANTITY DOUBLE,
	PRIMARY KEY (RECEIVED_PICK_ID)
);

CREATE TABLE DXRADMIN.REQUEST_WASTE_ITEM (
	REQUEST_WASTE_ITEM_ID VARCHAR(255) NOT NULL,
	WASTE_REQUEST_INFO_ID VARCHAR(255),
	WASTE_DEF_ID VARCHAR(255),
	PRIMARY KEY (REQUEST_WASTE_ITEM_ID)
);

CREATE TABLE DXRADMIN.ROLE_ACCESS_DEF (
	ROLE_ACCESS_DEF_ID VARCHAR(255) NOT NULL,
	ROLE_ID VARCHAR(255),
	ACCESS_DEF_ID VARCHAR(255),
	PRIMARY KEY (ROLE_ACCESS_DEF_ID)
);

CREATE TABLE DXRADMIN.ROLE_DEF (
	ROLE_DEF_ID VARCHAR(255) NOT NULL,
	ROLE_NAME VARCHAR(255),
	ROLE_CODE VARCHAR(255),
	ROLE_DESCRIPTION VARCHAR(255),
	COMPANY_CATEGORY_ID VARCHAR(255),
	PRIMARY KEY (ROLE_DEF_ID)
);

CREATE TABLE DXRADMIN.ROLE_DEF_UPDATE_FLAG (
	ROLE_DEF_UPDATE_FLAG_ID VARCHAR(255) NOT NULL,
	UPDATE_DATE VARCHAR(100),
	PRIMARY KEY (ROLE_DEF_UPDATE_FLAG_ID)
);

CREATE TABLE DXRADMIN.ROLE_MENU (
	ROLE_MENU_ID VARCHAR(255) NOT NULL,
	ROLE_DEF_ID VARCHAR(255),
	MENU_ID_LIST VARCHAR(12000),
	PRIMARY KEY (ROLE_MENU_ID)
);

CREATE TABLE DXRADMIN.ROLE_MENU_ACCESS_INFO (
	ROLE_MENU_ACCESS_INFO_ID VARCHAR(255) NOT NULL,
	ROLE_DEF_ID VARCHAR(255),
	MENU_ACCESS_BLOB BLOB(2147483647),
	UPDATE_DATE VARCHAR(255),
	PRIMARY KEY (ROLE_MENU_ACCESS_INFO_ID)
);

CREATE TABLE DXRADMIN.SCALE_INFO (
	SCALE_INFO_ID VARCHAR(255) NOT NULL,
	NAME_OF_SCALE VARCHAR(255),
	CAPACITY INTEGER,
	SCALE_NUMBER VARCHAR(255),
	QUANTITY INTEGER,
	REGISTRATION_NO VARCHAR(255),
	COMPANY_ID VARCHAR(255),
	PRIMARY KEY (SCALE_INFO_ID)
);

CREATE TABLE DXRADMIN.STATIC_PAGE (
	STATIC_PAGE_ID VARCHAR(255) NOT NULL,
	BACKEND_DATE VARCHAR(255),
	FRONTEND_DATE VARCHAR(255),
	STATIC_CONTENT_BYTES BLOB(2147483647),
	PRIMARY KEY (STATIC_PAGE_ID)
);

CREATE TABLE DXRADMIN.STATUS_INFO (
	STATUS_INFO_ID_PK VARCHAR(255) NOT NULL,
	PROJECT_INFO_ID VARCHAR(255),
	STATUS_DEF_ID VARCHAR(255),
	PRIMARY KEY (STATUS_INFO_ID_PK)
);

CREATE TABLE DXRADMIN.SUBSCRIPTION_COMPANY_CATAGORY (
	SUBSCRIPTION_COMPANY_CATEGORY_ID BIGINT GENERATED ALWAYS AS IDENTITY NOT NULL,
	SUBSCRIPTION_INFO VARCHAR(255),
	COMPANY_CATEGORY_ID_LIST VARCHAR(1024),
	PRIMARY KEY (SUBSCRIPTION_COMPANY_CATEGORY_ID)
);

CREATE TABLE DXRADMIN.SUBSCRIPTION_INFO (
	SUBSCRIPTION_INFO_ID VARCHAR(255) NOT NULL,
	COMPANY_NAME VARCHAR(255),
	ADDRESS VARCHAR(255),
	CONTACT_NO VARCHAR(255),
	EMAIL VARCHAR(255),
	AGREED_TERMS VARCHAR(255),
	DATE_TIME VARCHAR(255),
	SUBSCRIPTION_STATUS VARCHAR(255),
	IS_HUMAN VARCHAR(255),
	IS_AGREE VARCHAR(255),
	SUBSCRIBER_NAME VARCHAR(255),
	SUBSCRIBER_MAIL VARCHAR(255),
	ZIP_CODE VARCHAR(255),
	SUBSCRIBER_PASSWORD VARCHAR(1000),
	STATUS_ID VARCHAR(100),
	PRIMARY KEY (SUBSCRIPTION_INFO_ID)
);

CREATE TABLE DXRADMIN.SUBSCRIPTION_PROCESS_DEF (
	SUBSCRIPTION_PROCESS_DEF_ID VARCHAR(255) NOT NULL,
	SUBSCRIPTION_PROCESS_DEF VARCHAR(32500),
	PRIMARY KEY (SUBSCRIPTION_PROCESS_DEF_ID)
);

CREATE TABLE DXRADMIN.SUBSCRIPTION_STATUS (
	SUBSCRIPTION_STATUS_ID VARCHAR(255) NOT NULL,
	STATUS_TITLE VARCHAR(255),
	STATUS_CODE VARCHAR(255),
	PRIMARY KEY (SUBSCRIPTION_STATUS_ID)
);

CREATE TABLE DXRADMIN.TRANSPORTER_EMISSION_INFO (
	TRANSPORTER_EMISSION_ID VARCHAR(255) NOT NULL,
	COMPANY_ID VARCHAR(255),
	VEHICLE_ID VARCHAR(255),
	DATE_TIME VARCHAR(255),
	FUEL_QUANTITY DOUBLE,
	PRIMARY KEY (TRANSPORTER_EMISSION_ID)
);

CREATE TABLE DXRADMIN.TRIP_INFO (
	TRIP_INFO_ID VARCHAR(255) NOT NULL,
	PICK_UP_DATE VARCHAR(255),
	PICK_UP_TIME VARCHAR(255),
	DROP_TIME VARCHAR(255),
	VEHICLE_ID VARCHAR(255),
	DRIVER_ID VARCHAR(255),
	COMPANY_ID VARCHAR(255),
	PRIMARY KEY (TRIP_INFO_ID)
);

CREATE TABLE DXRADMIN.USER_ACCESS_INFO (
	USER_ACCESS_INFO_ID VARCHAR(255) NOT NULL,
	USER_IDENTIFICATION VARCHAR(255),
	ACCESS_INFO_BYTES BLOB(2147483647),
	UPDATE_DATE VARCHAR(255),
	PRIMARY KEY (USER_ACCESS_INFO_ID)
);

CREATE TABLE DXRADMIN.USER_CATEGORY (
	USER_CATEGORY_ID VARCHAR(255) NOT NULL,
	USER_CATEGORY_TITLE VARCHAR(255),
	USER_CATEGORY_CODE VARCHAR(255),
	USER_CATEGORY_DESCRIPTION VARCHAR(255),
	PRIMARY KEY (USER_CATEGORY_ID)
);

CREATE TABLE DXRADMIN.USER_IDENTIFICATION (
	USER_IDENTIFICATION_ID VARCHAR(255) NOT NULL,
	USER_ID VARCHAR(255),
	USER_AUTH VARCHAR(255),
	ONE_TIME_ACCESS_FLAG VARCHAR(255),
	PRIMARY KEY (USER_IDENTIFICATION_ID)
);

CREATE TABLE DXRADMIN.USER_INFO (
	USER_INFO_ID VARCHAR(255) NOT NULL,
	USER_NAME VARCHAR(255),
	USER_EMAIL VARCHAR(255),
	USER_CONTACT VARCHAR(255),
	USER_ADDRESS VARCHAR(255),
	DEPARTMENT_TITLE VARCHAR(255),
	USER_COMPANY_ID VARCHAR(255),
	USER_AUTH_ID VARCHAR(255),
	USER_CATEGORY_ID VARCHAR(255),
	JOB_TITLE VARCHAR(255),
	DRIVING_LICENSE_NO VARCHAR(255),
	DRIVING_LICENSE_BYTES BLOB(2147483647),
	OFFICE_NAME VARCHAR(255),
	OFFICE_ADDRESS VARCHAR(255),
	OFFICE_CONTACT_NO VARCHAR(255),
	USER_ID VARCHAR(255),
	REMARKS VARCHAR(255),
	USER_SEAL_BYTES BLOB(2147483647),
	PRIMARY KEY (USER_INFO_ID)
);

CREATE TABLE DXRADMIN.USER_ROLE_DEF (
	USER_ROLE_DEF_ID VARCHAR(255) NOT NULL,
	USER_IDENTIFICATION_ID VARCHAR(255),
	COMPANY_ID VARCHAR(255),
	ROLE_ID_LIST VARCHAR(5000),
	PRIMARY KEY (USER_ROLE_DEF_ID)
);

CREATE TABLE DXRADMIN.USER_SESSION (
	USER_SESSION_ID VARCHAR(255) NOT NULL,
	USER_SESSION_EMAIL VARCHAR(255),
	USER_SESSION_START_DATE VARCHAR(255),
	PRIMARY KEY (USER_SESSION_ID)
);

CREATE TABLE DXRADMIN.VEHICLE_GASOLIN (
	VEHICLE_GASOLIN_ID VARCHAR(255) NOT NULL,
	GASOLIN_ID VARCHAR(255),
	VEHICLE_TYPE_ID VARCHAR(255),
	VEHICLE_INFO_ID VARCHAR(255),
	PRIMARY KEY (VEHICLE_GASOLIN_ID)
);

CREATE TABLE DXRADMIN.VEHICLE_INFO (
	VEHICLE_INFO_ID VARCHAR(255) NOT NULL,
	MENUFACTURER_NAME VARCHAR(255),
	MODEL_NAME VARCHAR(255),
	VEHICLE_REG_NO VARCHAR(255),
	VEHICLE_CAPACITY VARCHAR(255),
	VEHICLE_WEIGHT VARCHAR(255),
	INSPECTION_DATE VARCHAR(255),
	VEHICLE_OWNER_SHIP_LIST VARCHAR(1200),
	REMARKS VARCHAR(32000),
	FRONTEND_DATE VARCHAR(255),
	BACKEND_DATE VARCHAR(255),
	COMPANY_INFO_ID VARCHAR(255),
	ZIPCODE VARCHAR(255),
	FITNESS_LICENSE_BYTE BLOB(2147483647),
	OFFICE_ADDRESS VARCHAR(255),
	PRIMARY KEY (VEHICLE_INFO_ID)
);

CREATE TABLE DXRADMIN.VEHICLE_TYPE (
	VEHICLE_TYPE_ID VARCHAR(255) NOT NULL,
	VEHICLE_TITLE VARCHAR(255),
	CODE VARCHAR(255),
	DESCRIPTIONS VARCHAR(255),
	GASOLIN_TYPE_LIST VARCHAR(555),
	DEFAULT_GASOLIN_TYPE_ID VARCHAR(255),
	PRIMARY KEY (VEHICLE_TYPE_ID)
);

CREATE TABLE DXRADMIN.WASTE_CATEGORY (
	WASTE_CATEGORY_ID VARCHAR(255) NOT NULL,
	WASTE_TITLE VARCHAR(255),
	CODE VARCHAR(255),
	DESCRIPTION VARCHAR(255),
	PRIMARY KEY (WASTE_CATEGORY_ID)
);

CREATE TABLE DXRADMIN.WASTE_DEF (
	WASTE_DEF_ID VARCHAR(255) NOT NULL,
	WASTE_ITEM VARCHAR(255),
	REMARKS VARCHAR(32000),
	UNIT_DEF VARCHAR(255),
	WASTE_CATAGORY_ID VARCHAR(255),
	WASTE_SHAPE VARCHAR(255),
	WASTE_PACKAGE VARCHAR(255),
	DUMPER_EMISSION_DEFAULT_METHODE_ID VARCHAR(255),
	DUMPER_EMISSION_METHODE_ID_LIST VARCHAR(512),
	PROCESSOR_EMISSION_DEFAULT_METHODE_ID VARCHAR(255),
	PROCESSOR_EMISSION_METHODE_ID_LIST VARCHAR(512),
	PRIMARY KEY (WASTE_DEF_ID)
);

CREATE TABLE DXRADMIN.WASTE_PROCESS_INFO (
	WASTE_PROCESS_INFO_ID VARCHAR(255) NOT NULL,
	PROCESS_START_DATE VARCHAR(255),
	PROCESS_END_DATE VARCHAR(255),
	QUANTITY DOUBLE,
	UNIT VARCHAR(255),
	PRICE DOUBLE,
	WASTE_TYPE_ID VARCHAR(255),
	WASTE_ITEM_ID VARCHAR(255),
	PROJECT_INFO_ID VARCHAR(255),
	PRIMARY KEY (WASTE_PROCESS_INFO_ID)
);

CREATE TABLE DXRADMIN.WASTE_REQUEST_INFO (
	WASTE_REQUEST_INFO_ID VARCHAR(255) NOT NULL,
	COMPANY_ID VARCHAR(255),
	USER_ID VARCHAR(255),
	PERSON_NAME VARCHAR(255),
	CONTACT_NO VARCHAR(255),
	WASTE_TYPE VARCHAR(255),
	WASTE_ITEM VARCHAR(255),
	UNIT_DEF VARCHAR(255),
	WASTE_SHAPE VARCHAR(255),
	WASTE_PACKAGE VARCHAR(255),
	FRONTEND_DATE VARCHAR(255),
	BACKEND_DATE VARCHAR(255),
	PRIMARY KEY (WASTE_REQUEST_INFO_ID)
);

CREATE TABLE DXRADMIN.WASTE_REQUEST_RESPONSE_INFO (
	WASTE_REQUEST_RESPONSE_INFO_ID VARCHAR(255) NOT NULL,
	RESPONSE_TITLE VARCHAR(255),
	WASTE_REQUEST_INFO_ID VARCHAR(255),
	PRIMARY KEY (WASTE_REQUEST_RESPONSE_INFO_ID)
);

CREATE TABLE DXRADMIN.WASTE_TYPE (
	WASTE_TYPE_ID VARCHAR(255) NOT NULL,
	WASTE_TITLE VARCHAR(255),
	CODE VARCHAR(255),
	DESCRIPTION VARCHAR(255),
	WASTE_CATEGORY_ID VARCHAR(255),
	PRIMARY KEY (WASTE_TYPE_ID)
);


ALTER TABLE DXRADMIN.ACCOUNTANT_INFO
	ADD FOREIGN KEY (COMPANY_ID) 
	REFERENCES DXRADMIN.COMPANY_INFO (COMPANY_INFO_ID);



ALTER TABLE DXRADMIN.AGREEMENT_COMPANY_INFO
	ADD FOREIGN KEY (AGREEMENT_INFO_ID) 
	REFERENCES DXRADMIN.AGREEMENT_INFO (AGREEMENT_INFO_ID);


ALTER TABLE DXRADMIN.AGREEMENT_COMPANY_INFO
	ADD FOREIGN KEY (COMPANY_ID) 
	REFERENCES DXRADMIN.COMPANY_INFO (COMPANY_INFO_ID);


ALTER TABLE DXRADMIN.AGREEMENT_COMPANY_INFO
	ADD FOREIGN KEY (PAYMENT_METHOD_ID) 
	REFERENCES DXRADMIN.PAYMENT_METHOD_INFO (PAYMENT_METHOD_INFO_ID);


ALTER TABLE DXRADMIN.AGREEMENT_COMPANY_INFO
	ADD FOREIGN KEY (PERSON_IN_CHARGE_ID) 
	REFERENCES DXRADMIN.USER_INFO (USER_INFO_ID);



ALTER TABLE DXRADMIN.AGREEMENT_INFO
	ADD FOREIGN KEY (PROCESSOR_COMPANY_ID) 
	REFERENCES DXRADMIN.COMPANY_INFO (COMPANY_INFO_ID);


ALTER TABLE DXRADMIN.AGREEMENT_INFO
	ADD FOREIGN KEY (TRANSPORTER_COMPANY_ID) 
	REFERENCES DXRADMIN.COMPANY_INFO (COMPANY_INFO_ID);


ALTER TABLE DXRADMIN.AGREEMENT_INFO
	ADD FOREIGN KEY (DUMPER_COMPANY_ID) 
	REFERENCES DXRADMIN.COMPANY_INFO (COMPANY_INFO_ID);



ALTER TABLE DXRADMIN.AGREEMENT_WASTE_PROCESS_INFO
	ADD FOREIGN KEY (AGREEMENT_INFO_ID) 
	REFERENCES DXRADMIN.AGREEMENT_INFO (AGREEMENT_INFO_ID);


ALTER TABLE DXRADMIN.AGREEMENT_WASTE_PROCESS_INFO
	ADD FOREIGN KEY (WASTE_DEF_ID) 
	REFERENCES DXRADMIN.WASTE_DEF (WASTE_DEF_ID);


ALTER TABLE DXRADMIN.AGREEMENT_WASTE_PROCESS_INFO
	ADD FOREIGN KEY (WASTE_CATEGORY_ID) 
	REFERENCES DXRADMIN.WASTE_TYPE (WASTE_TYPE_ID);



ALTER TABLE DXRADMIN.AGREEMENT_WASTE_TRANSPORT_INFO
	ADD FOREIGN KEY (AGREEMENT_INFO_ID) 
	REFERENCES DXRADMIN.AGREEMENT_INFO (AGREEMENT_INFO_ID);


ALTER TABLE DXRADMIN.AGREEMENT_WASTE_TRANSPORT_INFO
	ADD FOREIGN KEY (WASTE_DEF_ID) 
	REFERENCES DXRADMIN.WASTE_DEF (WASTE_DEF_ID);


ALTER TABLE DXRADMIN.AGREEMENT_WASTE_TRANSPORT_INFO
	ADD FOREIGN KEY (WASTE_CATEGORY_ID) 
	REFERENCES DXRADMIN.WASTE_TYPE (WASTE_TYPE_ID);



ALTER TABLE DXRADMIN.BANK_ACCOUNT_INFO
	ADD FOREIGN KEY (COMPANY_ID) 
	REFERENCES DXRADMIN.COMPANY_INFO (COMPANY_INFO_ID);



ALTER TABLE DXRADMIN.BASE_PRICE
	ADD FOREIGN KEY (COMPANY_WASTE_ID) 
	REFERENCES DXRADMIN.COMPANY_WASTE_DEF (COMPANY_WASTE_DEF_ID);



ALTER TABLE DXRADMIN.BRANCH_BUSINESS_TYPE
	ADD FOREIGN KEY (BRANCH_INFO_ID) 
	REFERENCES DXRADMIN.BRANCH_INFO (BRANCH_INFO_ID);



ALTER TABLE DXRADMIN.BRANCH_INFO
	ADD FOREIGN KEY (COMPANY_INFO_ID) 
	REFERENCES DXRADMIN.COMPANY_INFO (COMPANY_INFO_ID);



ALTER TABLE DXRADMIN.CARBON_EMISSION_METHOD_INFO
	ADD FOREIGN KEY (OPERATION_TYPE_ID) 
	REFERENCES DXRADMIN.OPERATION_TYPE (OPERATION_TYPE_ID);



ALTER TABLE DXRADMIN.COMPANY_INFO
	ADD FOREIGN KEY (NOTIFICATION_ID) 
	REFERENCES DXRADMIN.NOTIFICATION (NOTIFICATION_ID);


ALTER TABLE DXRADMIN.COMPANY_INFO
	ADD FOREIGN KEY (SUBSCRIPTION_ID) 
	REFERENCES DXRADMIN.SUBSCRIPTION_INFO (SUBSCRIPTION_INFO_ID);



ALTER TABLE DXRADMIN.COMPANY_WASTE_DEF
	ADD FOREIGN KEY (COMPANY_ID) 
	REFERENCES DXRADMIN.COMPANY_INFO (COMPANY_INFO_ID);


ALTER TABLE DXRADMIN.COMPANY_WASTE_DEF
	ADD FOREIGN KEY (WASTE_DEF_ID) 
	REFERENCES DXRADMIN.WASTE_DEF (WASTE_DEF_ID);



ALTER TABLE DXRADMIN.COMPANY_WASTE_OPERATION_METHOD_INFO
	ADD FOREIGN KEY (METHOD_ID) 
	REFERENCES DXRADMIN.CARBON_EMISSION_METHOD_INFO (EMISSION_METHOD_ID);


ALTER TABLE DXRADMIN.COMPANY_WASTE_OPERATION_METHOD_INFO
	ADD FOREIGN KEY (COMPANY_ID) 
	REFERENCES DXRADMIN.COMPANY_INFO (COMPANY_INFO_ID);


ALTER TABLE DXRADMIN.COMPANY_WASTE_OPERATION_METHOD_INFO
	ADD FOREIGN KEY (METHOD_TYPE_ID) 
	REFERENCES DXRADMIN.OPERATION_TYPE (OPERATION_TYPE_ID);


ALTER TABLE DXRADMIN.COMPANY_WASTE_OPERATION_METHOD_INFO
	ADD FOREIGN KEY (WASTE_ID) 
	REFERENCES DXRADMIN.WASTE_DEF (WASTE_DEF_ID);



ALTER TABLE DXRADMIN.DISPOSAL_INFO
	ADD FOREIGN KEY (COLLECTION_ID) 
	REFERENCES DXRADMIN.AGREEMENT_WASTE_TRANSPORT_INFO (AGREEMENT_WASTE_TRANSPORT_INFO_ID);


ALTER TABLE DXRADMIN.DISPOSAL_INFO
	ADD FOREIGN KEY (PROJECT_INFO_ID) 
	REFERENCES DXRADMIN.PROJECT_INFO (PROJECT_INFO_ID);



ALTER TABLE DXRADMIN.DUMPING_EMISSION_INFO
	ADD FOREIGN KEY (COMPANY_ID) 
	REFERENCES DXRADMIN.COMPANY_INFO (COMPANY_INFO_ID);



ALTER TABLE DXRADMIN.FAQ_INFO
	ADD FOREIGN KEY (FAQ_TYPE_ID) 
	REFERENCES DXRADMIN.FAQ_TYPE (FAQ_TYPE_ID);



ALTER TABLE DXRADMIN.INQUIRY_REPLY
	ADD FOREIGN KEY (INQUIRY_ID) 
	REFERENCES DXRADMIN.INQUIRY_INFO (INQUIRY_INFO_ID);



ALTER TABLE DXRADMIN.INQUIRY_RESPONSE
	ADD FOREIGN KEY (INQUIRY_INFO_ID) 
	REFERENCES DXRADMIN.INQUIRY_INFO (INQUIRY_INFO_ID);



ALTER TABLE DXRADMIN.MENU_DEF
	ADD FOREIGN KEY (MENU_CATEGORY_ID) 
	REFERENCES DXRADMIN.MENU_CATEGORY (MENU_CATEGORY_ID);


ALTER TABLE DXRADMIN.MENU_DEF
	ADD FOREIGN KEY (MENU_TYPE_ID) 
	REFERENCES DXRADMIN.MENU_TYPE (MENU_TYPE_ID);



ALTER TABLE DXRADMIN.MENU_ROLE_ACCESS
	ADD FOREIGN KEY (MENU_DEF_ID) 
	REFERENCES DXRADMIN.MENU_DEF (MENU_ID);



ALTER TABLE DXRADMIN.PACKAGE_INFO
	ADD FOREIGN KEY (DISPOSE_ID) 
	REFERENCES DXRADMIN.DISPOSAL_INFO (DISPOSAL_INFO_ID);


ALTER TABLE DXRADMIN.PACKAGE_INFO
	ADD FOREIGN KEY (PICK_ID) 
	REFERENCES DXRADMIN.PICK_INFO (PICK_INFO_ID);


ALTER TABLE DXRADMIN.PACKAGE_INFO
	ADD FOREIGN KEY (TRIP_ID) 
	REFERENCES DXRADMIN.TRIP_INFO (TRIP_INFO_ID);



ALTER TABLE DXRADMIN.PARTNER_COMPANY_INFO
	ADD FOREIGN KEY (PARTNER_ID) 
	REFERENCES DXRADMIN.COMPANY_INFO (COMPANY_INFO_ID);


ALTER TABLE DXRADMIN.PARTNER_COMPANY_INFO
	ADD FOREIGN KEY (COMPANY_ID) 
	REFERENCES DXRADMIN.COMPANY_INFO (COMPANY_INFO_ID);



ALTER TABLE DXRADMIN.PAYMENT_METHOD_INFO
	ADD FOREIGN KEY (AGREEMENT_INFO_ID) 
	REFERENCES DXRADMIN.AGREEMENT_INFO (AGREEMENT_INFO_ID);


ALTER TABLE DXRADMIN.PAYMENT_METHOD_INFO
	ADD FOREIGN KEY (COMPANY_ID) 
	REFERENCES DXRADMIN.COMPANY_INFO (COMPANY_INFO_ID);



ALTER TABLE DXRADMIN.PICK_INFO
	ADD FOREIGN KEY (DISPOSAL_ID) 
	REFERENCES DXRADMIN.DISPOSAL_INFO (DISPOSAL_INFO_ID);


ALTER TABLE DXRADMIN.PICK_INFO
	ADD FOREIGN KEY (TRIP_ID) 
	REFERENCES DXRADMIN.TRIP_INFO (TRIP_INFO_ID);



ALTER TABLE DXRADMIN.PREVILAGED_USER
	ADD FOREIGN KEY (COMPANY_ID) 
	REFERENCES DXRADMIN.COMPANY_INFO (COMPANY_INFO_ID);


ALTER TABLE DXRADMIN.PREVILAGED_USER
	ADD FOREIGN KEY (USER_ID) 
	REFERENCES DXRADMIN.USER_IDENTIFICATION (USER_IDENTIFICATION_ID);



ALTER TABLE DXRADMIN.PROCESSING_EMISSION_INFO
	ADD FOREIGN KEY (COMPANY_ID) 
	REFERENCES DXRADMIN.COMPANY_INFO (COMPANY_INFO_ID);



ALTER TABLE DXRADMIN.PROJECT_INFO
	ADD FOREIGN KEY (AGREEMENT_INFO_ID) 
	REFERENCES DXRADMIN.AGREEMENT_INFO (AGREEMENT_INFO_ID);


ALTER TABLE DXRADMIN.PROJECT_INFO
	ADD FOREIGN KEY (COMPANY_ID) 
	REFERENCES DXRADMIN.COMPANY_INFO (COMPANY_INFO_ID);



ALTER TABLE DXRADMIN.RECEIVED_PICK
	ADD FOREIGN KEY (PICK_ID) 
	REFERENCES DXRADMIN.PICK_INFO (PICK_INFO_ID);



ALTER TABLE DXRADMIN.REQUEST_WASTE_ITEM
	ADD FOREIGN KEY (WASTE_DEF_ID) 
	REFERENCES DXRADMIN.WASTE_DEF (WASTE_DEF_ID);


ALTER TABLE DXRADMIN.REQUEST_WASTE_ITEM
	ADD FOREIGN KEY (WASTE_REQUEST_INFO_ID) 
	REFERENCES DXRADMIN.WASTE_REQUEST_INFO (WASTE_REQUEST_INFO_ID);



ALTER TABLE DXRADMIN.ROLE_ACCESS_DEF
	ADD FOREIGN KEY (ACCESS_DEF_ID) 
	REFERENCES DXRADMIN.ACCESS_DEF (ACCESS_DEF_ID);


ALTER TABLE DXRADMIN.ROLE_ACCESS_DEF
	ADD FOREIGN KEY (ROLE_ID) 
	REFERENCES DXRADMIN.ROLE_DEF (ROLE_DEF_ID);



ALTER TABLE DXRADMIN.ROLE_MENU
	ADD FOREIGN KEY (ROLE_DEF_ID) 
	REFERENCES DXRADMIN.ROLE_DEF (ROLE_DEF_ID);



ALTER TABLE DXRADMIN.ROLE_MENU_ACCESS_INFO
	ADD FOREIGN KEY (ROLE_DEF_ID) 
	REFERENCES DXRADMIN.ROLE_DEF (ROLE_DEF_ID);



ALTER TABLE DXRADMIN.SCALE_INFO
	ADD FOREIGN KEY (COMPANY_ID) 
	REFERENCES DXRADMIN.COMPANY_INFO (COMPANY_INFO_ID);



ALTER TABLE DXRADMIN.SUBSCRIPTION_COMPANY_CATAGORY
	ADD FOREIGN KEY (SUBSCRIPTION_INFO) 
	REFERENCES DXRADMIN.SUBSCRIPTION_INFO (SUBSCRIPTION_INFO_ID);



ALTER TABLE DXRADMIN.SUBSCRIPTION_INFO
	ADD FOREIGN KEY (SUBSCRIPTION_STATUS) 
	REFERENCES DXRADMIN.SUBSCRIPTION_STATUS (SUBSCRIPTION_STATUS_ID);



ALTER TABLE DXRADMIN.TRANSPORTER_EMISSION_INFO
	ADD FOREIGN KEY (COMPANY_ID) 
	REFERENCES DXRADMIN.COMPANY_INFO (COMPANY_INFO_ID);


ALTER TABLE DXRADMIN.TRANSPORTER_EMISSION_INFO
	ADD FOREIGN KEY (VEHICLE_ID) 
	REFERENCES DXRADMIN.VEHICLE_INFO (VEHICLE_INFO_ID);



ALTER TABLE DXRADMIN.TRIP_INFO
	ADD FOREIGN KEY (COMPANY_ID) 
	REFERENCES DXRADMIN.COMPANY_INFO (COMPANY_INFO_ID);


ALTER TABLE DXRADMIN.TRIP_INFO
	ADD FOREIGN KEY (DRIVER_ID) 
	REFERENCES DXRADMIN.USER_INFO (USER_INFO_ID);


ALTER TABLE DXRADMIN.TRIP_INFO
	ADD FOREIGN KEY (VEHICLE_ID) 
	REFERENCES DXRADMIN.VEHICLE_INFO (VEHICLE_INFO_ID);



ALTER TABLE DXRADMIN.USER_ACCESS_INFO
	ADD FOREIGN KEY (USER_IDENTIFICATION) 
	REFERENCES DXRADMIN.USER_IDENTIFICATION (USER_IDENTIFICATION_ID);



ALTER TABLE DXRADMIN.USER_INFO
	ADD FOREIGN KEY (USER_COMPANY_ID) 
	REFERENCES DXRADMIN.COMPANY_INFO (COMPANY_INFO_ID);


ALTER TABLE DXRADMIN.USER_INFO
	ADD FOREIGN KEY (USER_CATEGORY_ID) 
	REFERENCES DXRADMIN.USER_CATEGORY (USER_CATEGORY_ID);


ALTER TABLE DXRADMIN.USER_INFO
	ADD FOREIGN KEY (USER_AUTH_ID) 
	REFERENCES DXRADMIN.USER_IDENTIFICATION (USER_IDENTIFICATION_ID);



ALTER TABLE DXRADMIN.USER_ROLE_DEF
	ADD FOREIGN KEY (COMPANY_ID) 
	REFERENCES DXRADMIN.COMPANY_INFO (COMPANY_INFO_ID);


ALTER TABLE DXRADMIN.USER_ROLE_DEF
	ADD FOREIGN KEY (USER_IDENTIFICATION_ID) 
	REFERENCES DXRADMIN.USER_IDENTIFICATION (USER_IDENTIFICATION_ID);



ALTER TABLE DXRADMIN.VEHICLE_GASOLIN
	ADD FOREIGN KEY (GASOLIN_ID) 
	REFERENCES DXRADMIN.GASOLINE_TYPE (GASOLINE_TYPE_ID);


ALTER TABLE DXRADMIN.VEHICLE_GASOLIN
	ADD FOREIGN KEY (VEHICLE_INFO_ID) 
	REFERENCES DXRADMIN.VEHICLE_INFO (VEHICLE_INFO_ID);


ALTER TABLE DXRADMIN.VEHICLE_GASOLIN
	ADD FOREIGN KEY (VEHICLE_TYPE_ID) 
	REFERENCES DXRADMIN.VEHICLE_TYPE (VEHICLE_TYPE_ID);



ALTER TABLE DXRADMIN.VEHICLE_INFO
	ADD FOREIGN KEY (COMPANY_INFO_ID) 
	REFERENCES DXRADMIN.COMPANY_INFO (COMPANY_INFO_ID);



ALTER TABLE DXRADMIN.VEHICLE_TYPE
	ADD FOREIGN KEY (DEFAULT_GASOLIN_TYPE_ID) 
	REFERENCES DXRADMIN.GASOLINE_TYPE (GASOLINE_TYPE_ID);



ALTER TABLE DXRADMIN.WASTE_DEF
	ADD FOREIGN KEY (WASTE_CATAGORY_ID) 
	REFERENCES DXRADMIN.WASTE_TYPE (WASTE_TYPE_ID);



ALTER TABLE DXRADMIN.WASTE_PROCESS_INFO
	ADD FOREIGN KEY (PROJECT_INFO_ID) 
	REFERENCES DXRADMIN.PROJECT_INFO (PROJECT_INFO_ID);


ALTER TABLE DXRADMIN.WASTE_PROCESS_INFO
	ADD FOREIGN KEY (WASTE_ITEM_ID) 
	REFERENCES DXRADMIN.WASTE_DEF (WASTE_DEF_ID);


ALTER TABLE DXRADMIN.WASTE_PROCESS_INFO
	ADD FOREIGN KEY (WASTE_TYPE_ID) 
	REFERENCES DXRADMIN.WASTE_TYPE (WASTE_TYPE_ID);



ALTER TABLE DXRADMIN.WASTE_REQUEST_INFO
	ADD FOREIGN KEY (COMPANY_ID) 
	REFERENCES DXRADMIN.COMPANY_INFO (COMPANY_INFO_ID);


ALTER TABLE DXRADMIN.WASTE_REQUEST_INFO
	ADD FOREIGN KEY (USER_ID) 
	REFERENCES DXRADMIN.USER_INFO (USER_INFO_ID);



ALTER TABLE DXRADMIN.WASTE_REQUEST_RESPONSE_INFO
	ADD FOREIGN KEY (WASTE_REQUEST_INFO_ID) 
	REFERENCES DXRADMIN.WASTE_REQUEST_INFO (WASTE_REQUEST_INFO_ID);



ALTER TABLE DXRADMIN.WASTE_TYPE
	ADD FOREIGN KEY (WASTE_CATEGORY_ID) 
	REFERENCES DXRADMIN.WASTE_CATEGORY (WASTE_CATEGORY_ID);



-- 2022-05-29

CREATE TABLE DXRADMIN.invoice_process_def  (
    invoice_process_def_id VARCHAR(255) NOT NULL,
    invoice_process_def VARCHAR(32500),
    PRIMARY KEY (invoice_process_def_id)
);

CREATE TABLE DXRADMIN.user_session  (
    user_session_id VARCHAR(255) NOT NULL,
    user_session_email VARCHAR(255),
    user_session_start_date VARCHAR(255),
    PRIMARY KEY (user_session_id)
);

ALTER TABLE DXRADMIN.subscription_info ADD status_id VARCHAR(100) DEFAULT 'statusInUse';


CREATE TABLE DXRADMIN.subscription_process_def  (
    subscription_process_def_id VARCHAR(255) NOT NULL,
    subscription_process_def VARCHAR(32500),
    PRIMARY KEY (subscription_process_def_id)
);

CREATE TABLE DXRADMIN.subscription_invite_info  (
    invitation_id VARCHAR(255) NOT NULL,
    sender_company_name VARCHAR(255),
    sender_email VARCHAR(255),
    receiver_company_name VARCHAR(255),
    receiver_email VARCHAR(255),
    PRIMARY KEY (invitation_id)
);